export const API_START = "API_START";
export const API_END = "API_END";
export const API_ERROR = "API_ERROR";
export const FETCH_EXPENSE_AMOUNT = "FETCH_EXPENSE_AMOUNT";
export const FETCH_INCOME_AMOUNT = "FETCH_INCOME_AMOUNT";
export const POST_EXPENSE_AMOUNT = "POST_EXPENSE_AMOUNT";
export const POST_INCOME_AMOUNT = "POST_INCOME_AMOUNT";
export const SET_EXPENSE_AMOUNT = "SET_EXPENSE_AMOUNT";
export const ADD_EXPENSE_AMOUNT = "ADD_EXPENSE_AMOUNT";
export const ADD_EXPENSE_CATEGORY = "ADD_EXPENSE_CATEGORY";
export const SET_INCOMES_DIAGRAMM_VALUES = "SET_INCOMES_DIAGRAMM_VALUES";
export const SET_INCOME = 'SET_INCOME';
export const FETCH_CURRENCY_DATA = 'FETCH_CURRENCY_DATA';
export const SET_CURRENCY_DATA = 'SET_CURRENCY_DATA';




